const product  = [{
    "id": 0,
    "brand": "NIKE",
    "model": "SNEAKERS",
    "color": "NEGRO",
    "price": 6000,
    "sale": true,
},
{
    "id": 1,
    "brand": "PUMA",
    "model": "SNEAKERS",
    "color": "BLANCO",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 2,
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "VERDE",
    "price": 10000,
    "sale": false,
  },
  {
    "id": 3,
    "brand": "PUMA",
    "model": "RUNNING",
    "color": "GRIS",
    "price": 4000,
    "sale": true,
  },
  {
    "id": 4,
    "brand": "ADIDAS",
    "model": "SNEAKERS",
    "color": "AZUL",
    "price": 10000,
    "sale": false,
  },
  {
    "id": 5,
    "brand": "NIKE",
    "model": "SNEAKERS",
    "color": "BEIGE",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 6,
    "brand": "PUMA",
    "model": "SPORT",
    "color": "VERDE",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 7,
    "brand": "NIKE",
    "model": "RUNNING",
    "color": "NARANJA",
    "price": 6000,
    "sale": true,
  },
  {
    "id": 8,
    "brand": "NIKE",
    "model": "SPORT",
    "color": "ROSA",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 9,
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "ROJO",
    "price": 5000,
    "sale": true,
  },
  {
    "id": 10,
    "brand": "PUMA",
    "model": "RUNNING",
    "color": "VIOLETA",
    "price": 4000,
    "sale": true,
  },
  {
    "id": 11,
    "brand": "NIKE",
    "model": "SPORT",
    "color": "BLANCO",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 12,
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "BLANCO",
    "price": 5000,
    "sale": true,
  },
  {
    "id": 13,
    "brand": "PUMA",
    "model": "SNEAKERS",
    "color": "ROSA",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 14,
    "brand": "ADIDAS",
    "model": "SPORT",
    "color": "NEGRO",
    "price": 10000,
    "sale": false
  }
];