const product  = [{
    "id": 1,
    "brand": "ADIDAS",
    "model": "Sneakers",
    "color": "BLACK",
    "price": 7000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/adidas-black.jpg",
    "sale": true,
},
{
    "id": 2,
    "brand": "ADIDAS",
    "model": "Sneakers",
    "color": "BLUE",
    "price": 10000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/adidas-blue.jpg",
    "sale": false,
  },
  {
    "id": 3,
    "brand": "ADIDAS",
    "model": "Sneakers",
    "color": "GREEN",
    "price": 10000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/adidas-green.jpg",
    "sale": false,
  },
  {
    "id": 4,
    "brand": "ADIDAS",
    "model": "Sneakers",
    "color": "RED",
    "price": 7000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/adidas-red.jpg",
    "sale": true,
  },
  {
    "id": 5,
    "brand": "ADIDAS",
    "model": "Sneakers",
    "color": "WHITE",
    "price": 10000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/adidas-white.jpg",
    "sale": false,
  },
  {
    "id": 6,
    "brand": "NIKE",
    "model": "Airmax",
    "color": "BEIGE",
    "price": 12000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/nike-beige.jpg",
    "sale": false,
  },
  {
    "id": 7,
    "brand": "NIKE",
    "model": "Airmax",
    "color": "BLACK",
    "price": 9000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/nike-black.jpg",
    "sale": true,
  },
  {
    "id": 8,
    "brand": "NIKE",
    "model": "Airmax",
    "color": "ORANGE",
    "price": 9000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/nike-orange.jpg",
    "sale": true,
  },
  {
    "id": 9,
    "brand": "NIKE",
    "model": "Airmax",
    "color": "PINK",
    "price": 12000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/nike-purple.jpg",
    "sale": false,
  },
  {
    "id": 10,
    "brand": "NIKE",
    "model": "Airmax",
    "color": "WHITE",
    "price": 12000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/nike-white.jpg",
    "sale": false,
  },
  {
    "id": 11,
    "brand": "PUMA",
    "model": "x-Ray",
    "color": "PINK",
    "price": 5000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/puma-colors.jpg",
    "sale": true,
  },
  {
    "id": 12,
    "brand": "PUMA",
    "model": "x-Ray",
    "color": "GREEN",
    "price": 5000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/puma-green.jpg",
    "sale": true,
  },
  {
    "id": 13,
    "brand": "PUMA",
    "model": "x-Ray",
    "color": "GREY",
    "price": 5000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/puma-grey.jpg",
    "sale": true,
  },
  {
    "id": 14,
    "brand": "PUMA",
    "model": "x-Ray",
    "color": "PINK",
    "price": 8000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/puma-pink.jpg",
    "sale": false,
  },
  {
    "id": 15,
    "brand": "PUMA",
    "model": "x-Ray",
    "color": "WHITE",
    "price": 8000,
    "img": "https://raw.githubusercontent.com/AgustinBraco/javascript/master/assets/puma-white.jpg",
    "sale": false,
  }
]

