const product  = [{
    "id": 0,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/nike-black.jpg?raw=true",
    "brand": "NIKE",
    "model": "SNEAKERS",
    "color": "NEGRO",
    "price": 6000,
    "sale": true,
},
{
    "id": 1,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/puma-white.jpg?raw=true",
    "brand": "PUMA",
    "model": "SNEAKERS",
    "color": "BLANCO",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 2,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/adidas-green.jpg?raw=true",
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "VERDE",
    "price": 10000,
    "sale": false,
  },
  {
    "id": 3,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/puma-grey.jpg?raw=true",
    "brand": "PUMA",
    "model": "RUNNING",
    "color": "GRIS",
    "price": 4000,
    "sale": true,
  },
  {
    "id": 4,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/adidas-blue.jpg?raw=true",
    "brand": "ADIDAS",
    "model": "SNEAKERS",
    "color": "AZUL",
    "price": 10000,
    "sale": false,
  },
  {
    "id": 5,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/nike-beige.jpg?raw=true",
    "brand": "NIKE",
    "model": "SNEAKERS",
    "color": "BEIGE",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 6,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/puma-green.jpg?raw=true",
    "brand": "PUMA",
    "model": "SPORT",
    "color": "VERDE",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 7,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/nike-orange.jpg?raw=true",
    "brand": "NIKE",
    "model": "RUNNING",
    "color": "NARANJA",
    "price": 6000,
    "sale": true,
  },
  {
    "id": 8,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/nike-purple.jpg?raw=true",
    "brand": "NIKE",
    "model": "SPORT",
    "color": "ROSA",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 9,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/adidas-red.jpg?raw=true",
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "ROJO",
    "price": 5000,
    "sale": true,
  },
  {
    "id": 10,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/puma-colors.jpg?raw=true",
    "brand": "PUMA",
    "model": "RUNNING",
    "color": "COLORES",
    "price": 4000,
    "sale": true,
  },
  {
    "id": 11,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/nike-white.jpg?raw=true",
    "brand": "NIKE",
    "model": "SPORT",
    "color": "BLANCO",
    "price": 12000,
    "sale": false,
  },
  {
    "id": 12,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/adidas-white.jpg?raw=true",
    "brand": "ADIDAS",
    "model": "RUNNING",
    "color": "BLANCO",
    "price": 5000,
    "sale": true,
  },
  {
    "id": 13,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/puma-pink.jpg?raw=true",
    "brand": "PUMA",
    "model": "SNEAKERS",
    "color": "ROSA",
    "price": 8000,
    "sale": false,
  },
  {
    "id": 14,
    "img": "https://github.com/AgustinBraco/javascript/blob/master/assets/adidas-black.jpg?raw=true",
    "brand": "ADIDAS",
    "model": "SPORT",
    "color": "NEGRO",
    "price": 10000,
    "sale": false
  }
];